# redis 配置
#spring:
#  redis:
#    host: 140.143.94.184
#    database: 0
#    port: 6379
#    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1
#        min-idle: 0
#    timeout: 0
spring:
  datasource:
    url: jdbc:mysql://140.143.94.184:3306/db_name?useUnicode=true&charcterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Hjl!!1991
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-idle: 1
      max-wait-millis: 60000
      initial-size: 1
    name: test
  redis:
    database: 0
    host: 140.143.94.184
    port: 6379
    password: 123456
    timeout: 10000
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml